### ISSUE TITLE
Adding new libarary libvmaf

### ISSUE THREAD

**Issue by jurisevo** [csnewman/ffmpeg-go#11]
Dear developers,

I am locally experimenting with adding a [libvmaf](https://github.com/Netflix/vmaf/tree/master/libvmaf) library to `ffmpeg-go`. As far as I have figured out I need to perfomr following steps:

1. Modify `internal/builder` accordingly to "build" new library.
2. Add header files under `include/libvmaf`.

This is where I get stuck, although I can build new `libffmpeg_linux_amd64.a` with libvmaf library, I get quite many build errors when trying to actually build some project using my modified `ffmepg-go`.

I have very little experience with Go an C interfacing, one noteworthy thing is that libvmaf contains C++ code and accordingly requires C++ tool-chain. I wonder if this may be causing issues with CGO?

My progress so far: https://github.com/csnewman/ffmpeg-go/pull/10

Any comments, ideas, suggestion will be appreciated.

**Comment by csnewman** [comment]
> 2. Add header files under include/libvmaf.

You shouldn't need to add the header files under `include/libvmaf` unless the underlying library needs exposing in Go. At the moment, this library only exposes the ffmpeg libraries and all the other dependencies have to be accessed via the ffmpeg api.

Harfbuzz is a c++ meson library that is already built, so should be a similar build process.

>  I get quite many build errors when trying to actually build some project using my modified ffmepg-go.

Do you have a copy of these errors? You're likely missing a dependency.

**Comment by jurisevo** [comment]
Hi, thanks for response!

Attaching errors I get when running `go test` in project root.

Also, good to know I don't need to add header files, will remove them.

[errors.txt](https://github.com/csnewman/ffmpeg-go/files/14901961/errors.txt)

**Comment by csnewman** [comment]
Does look to be missing the C++ standard library from those error messages. Adding `-lstdc++` to the `LDFLAGS` in `ffmpeg.go` should fix it.

**Comment by jurisevo** [comment]
> Does look to be missing the C++ standard library from those error messages. Adding `-lstdc++` to the `LDFLAGS` in `ffmpeg.go` should fix it.

Alright, that did the trick. Thank You!
